/* Generated by Nim Compiler v0.17.1 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -mno-ms-bitfields  -ID:\nim\lib -o d:\Documents\Programming\nim\nimbomb\src\resources\nimcache\nimbomb_game.o d:\Documents\Programming\nim\nimbomb\src\resources\nimcache\nimbomb_game.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_Game_WRZykltC6NzgW1YEXOG5pA tyObject_Game_WRZykltC6NzgW1YEXOG5pA;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_Game_WRZykltC6NzgW1YEXOG5pA {
NimStringDesc* apiName;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* fieldList;
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, newGame_OAedRPWpsyCXULP9aV8nA7Q)(tyObject_Game_WRZykltC6NzgW1YEXOG5pA* Result);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(tySequence_sM4lkSb7zS6F7OVMvW9cffQ*, getFieldList_v62FEUmv9ahSaNLbB9aJgURg)(NimStringDesc* res);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NimStringDesc*, dollar__ch0e5PgaoEZEQHhvsLrGJQ)(tySequence_sM4lkSb7zS6F7OVMvW9cffQ* x);
N_NIMCALL(NimStringDesc*, collectionToString_5rpXKhv6py1qh4AQd15Eog)(tySequence_sM4lkSb7zS6F7OVMvW9cffQ* x, NimStringDesc* b, NimStringDesc* e);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, nimbomb_fieldsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, nimbomb_fieldsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, gameDatInit000)(void);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
STRING_LITERAL(TM_c8t4fnaK9aMvz3fZUNqHt5g_2, "game", 4);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_NIMCALL(void, newGame_OAedRPWpsyCXULP9aV8nA7Q)(tyObject_Game_WRZykltC6NzgW1YEXOG5pA* Result) {
	nimfr_("newGame", "game.nim")
	nimln_(9, "game.nim");
	unsureAsgnRef((void**) (&(*Result).apiName), copyString(((NimStringDesc*) &TM_c8t4fnaK9aMvz3fZUNqHt5g_2)));
	nimln_(10, "game.nim");
	unsureAsgnRef((void**) (&(*Result).fieldList), getFieldList_v62FEUmv9ahSaNLbB9aJgURg(((NimStringDesc*) &TM_c8t4fnaK9aMvz3fZUNqHt5g_2)));
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_sequtilsDatInit000();
	nimbomb_fieldsDatInit000();
	gameDatInit000();
	stdlib_sequtilsInit000();
	nimbomb_fieldsInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	tyObject_Game_WRZykltC6NzgW1YEXOG5pA T1_;
	NimStringDesc* T2_;
	nimfr_("game", "game.nim")
	nimln_(12, "game.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	newGame_OAedRPWpsyCXULP9aV8nA7Q((&T1_));
	T2_ = (NimStringDesc*)0;
	T2_ = dollar__ch0e5PgaoEZEQHhvsLrGJQ(T1_.fieldList);
	printf("%s\015\012", T2_? (T2_)->data:"nil");
	fflush(stdout);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, gameDatInit000)(void) {
}

